services:
  api:
    build: ./server
    container_name: node_backend
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  web:
    image: node:20
    container_name: vite_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - api
    networks:
      - app-network

  db:
    image: mariadb:11.4 #image: mysql:8.0
    container_name: mariadb_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/new_init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./db/my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer_gui
    ports:
      - "${PORT_ADMINER}:8080"
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
